"""news_renderer — 科技日報 HTML 渲染（self-contained，零外部依賴）。"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from src.skills.base import BaseSkill, SkillParam, SkillResult, SkillType

# 內建 HTML 模板（暗黑科技風格，所有 CSS 內嵌）
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{date} 科技日報</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
  font-family: "Noto Sans TC", "Microsoft JhengHei", sans-serif;
  background: #0f1419; color: #e7e9ea;
  padding: 24px; min-height: 100vh;
}}
.header {{
  text-align: center; padding: 32px 0 24px;
  background: linear-gradient(135deg, #1a2332, #0f1419);
  border-bottom: 2px solid #2d3748;
  margin-bottom: 24px;
}}
.header h1 {{
  font-size: 28px; font-weight: 900;
  background: linear-gradient(90deg, #60a5fa, #a78bfa);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
}}
.header .subtitle {{ color: #8899a6; margin-top: 8px; font-size: 14px; }}
.card {{
  background: #1a2332; border: 1px solid #2d3748;
  border-radius: 12px; padding: 20px; margin-bottom: 16px;
  transition: border-color 0.2s;
}}
.card:hover {{ border-color: #60a5fa; }}
.card-header {{
  display: flex; align-items: center; gap: 12px; margin-bottom: 12px;
}}
.card-emoji {{ font-size: 24px; }}
.card-title {{ font-size: 18px; font-weight: 700; color: #f1f5f9; }}
.card-source {{ color: #8899a6; font-size: 12px; margin-top: 4px; }}
.card-body {{ color: #cbd5e1; font-size: 14px; line-height: 1.7; }}
.card-link {{
  display: inline-block; margin-top: 12px; color: #60a5fa;
  font-size: 13px; text-decoration: none;
}}
.card-link:hover {{ text-decoration: underline; }}
.footer {{
  text-align: center; color: #4a5568; font-size: 12px;
  margin-top: 32px; padding-top: 16px; border-top: 1px solid #2d3748;
}}
</style>
</head>
<body>
<div class="header">
  <h1>📡 科技日報</h1>
  <div class="subtitle">{date} ｜ 共 {count} 則新聞</div>
</div>

{cards_html}

<div class="footer">
  Generated by AI Agent Bot ｜ {date}
</div>
</body>
</html>"""

_CARD_TEMPLATE = """<div class="card">
  <div class="card-header">
    <span class="card-emoji">{emoji}</span>
    <div>
      <div class="card-title">{title}</div>
      <div class="card-source">{source}</div>
    </div>
  </div>
  <div class="card-body">{description}</div>
  {link_html}
</div>"""

# 分類 emoji
_TOPIC_EMOJI = {
    "ai": "🤖", "ai_focus": "🤖", "ai_skills": "🧩",
    "tech_general": "💡", "dev_tools": "🔧", "coding": "💻",
    "default": "📰",
}


class NewsRendererParams(SkillParam):
    """news_renderer 輸入參數。"""
    articles: list[dict] = []
    output_path: str = ""


class NewsRendererSkill(BaseSkill):
    """科技日報 HTML 渲染 — self-contained，瀏覽器直接開啟。"""

    skill_id = "news_renderer"
    skill_type = SkillType.PYTHON
    description = "科技日報 HTML 渲染（暗黑科技風格）"
    version = "2.0.0"
    input_schema = NewsRendererParams

    async def execute(self, params: dict) -> SkillResult:
        """渲染結構化新聞為 HTML 日報。"""
        try:
            p = NewsRendererParams(**params)
            now = datetime.now()
            date_str = now.strftime("%Y-%m-%d")
            date_display = now.strftime("%Y.%m.%d")

            # 產出每張卡片
            cards: list[str] = []
            for art in p.articles:
                emoji = self._get_emoji(art.get("topic", ""))
                title = art.get("title", "未知標題")
                source = art.get("source", "")
                desc = art.get("what") or art.get("description") or title
                url = art.get("url", "")

                link_html = f'<a class="card-link" href="{url}" target="_blank">🔗 閱讀原文</a>' if url else ""

                cards.append(_CARD_TEMPLATE.format(
                    emoji=emoji,
                    title=title[:60],
                    source=source,
                    description=desc[:300],
                    link_html=link_html,
                ))

            # 組裝完整 HTML
            html = _HTML_TEMPLATE.format(
                date=date_display,
                count=len(p.articles),
                cards_html="\n".join(cards),
            )

            # 寫檔
            output_path = p.output_path or f"output/news/tech-daily-{date_str}.html"
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            Path(output_path).write_text(html, encoding="utf-8")

            return SkillResult(success=True, data={
                "path": output_path,
                "count": len(p.articles),
                "size": len(html),
            })
        except Exception as e:
            return SkillResult(success=False, error=f"渲染失敗: {e}")

    def _get_emoji(self, topic: str) -> str:
        """根據分類取 emoji。"""
        topic_lower = topic.lower()
        for key, emoji in _TOPIC_EMOJI.items():
            if key in topic_lower:
                return emoji
        return _TOPIC_EMOJI["default"]
