"""Generator: src/business/ — 業務技能（news + web_search）"""
from pathlib import Path

FILES = {
    'business/__init__.py': '"""業務 Skills — 本地快速執行的功能模組。"""\n',
    'business/news_renderer.py': '"""news_renderer — 將新聞列表渲染為 HTML 日報。"""\nfrom __future__ import annotations\n\nfrom datetime import datetime, timezone\nfrom pathlib import Path\nfrom string import Template\n\nTEMPLATE_PATH = Path("templates/tech-daily.html")\nOUTPUT_DIR = Path("output")\n\n\nasync def render_daily(articles: list[dict], output_path: str = "") -> str:\n    """渲染日報 HTML，回傳檔案路徑。"""\n    if TEMPLATE_PATH.exists():\n        tpl = Template(TEMPLATE_PATH.read_text(encoding="utf-8"))\n    else:\n        tpl = Template(\n            "<!DOCTYPE html><html><head><meta charset=\'utf-8\'><title>Daily $date</title></head>"\n            "<body><h1>📰 Daily — $date</h1><ul>$items</ul></body></html>"\n        )\n\n    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")\n    items_html = "\\n".join(\n        f\'<li><a href="{a.get("url", "#")}">{a["title"]}</a> — {a.get("source", "")}</li>\'\n        for a in articles\n    )\n\n    html = tpl.safe_substitute(date=today, items=items_html, count=len(articles))\n    out = Path(output_path) if output_path else OUTPUT_DIR / f"daily-{today}.html"\n    out.parent.mkdir(parents=True, exist_ok=True)\n    out.write_text(html, encoding="utf-8")\n    return str(out)\n',
    'business/news_scraper.py': '"""news_scraper — 從多來源抓取科技新聞。"""\nfrom __future__ import annotations\n\nimport logging\nfrom pathlib import Path\n\nimport httpx\nimport yaml\nfrom bs4 import BeautifulSoup\n\nlog = logging.getLogger(__name__)\n\nCONFIG_PATH = Path("config/news_sources.yaml")\n\n\nasync def scrape_news(config_path: str | Path = CONFIG_PATH, limit: int = 10) -> list[dict]:\n    """抓取新聞，回傳 [{title, url, source}]。"""\n    cfg = Path(config_path)\n    if not cfg.exists():\n        return []\n    sources = yaml.safe_load(cfg.read_text(encoding="utf-8"))\n    articles: list[dict] = []\n\n    async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:\n        for source in sources.get("sources", []):\n            try:\n                r = await client.get(source["url"], headers={"User-Agent": "Mozilla/5.0"})\n                if r.status_code != 200:\n                    continue\n                soup = BeautifulSoup(r.text, "html.parser")\n                for el in soup.select(source.get("selector", "article"))[:5]:\n                    title_el = el.select_one(source.get("title_sel", "h2, h3, a"))\n                    link_el = el.select_one("a[href]")\n                    if title_el:\n                        articles.append({\n                            "title": title_el.get_text(strip=True),\n                            "url": link_el["href"] if link_el else "",\n                            "source": source.get("name", ""),\n                        })\n            except Exception as e:\n                log.debug("Scrape %s failed: %s", source.get("name"), e)\n\n    return articles[:limit]\n',
    'business/web_search.py': '"""web_search — 快速網路搜尋（透過 Gemini grounding）。"""\nfrom __future__ import annotations\n\nimport os\nimport httpx\n\n\nasync def web_search(query: str, limit: int = 5) -> list[dict]:\n    """用 Gemini API 搜尋網路，回傳 [{title, snippet, url}]。"""\n    api_key = os.getenv("GEMINI_API_KEY", "")\n    if not api_key:\n        return []\n\n    model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")\n    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"\n\n    prompt = f"搜尋以下主題，列出前 {limit} 個相關結果（標題 + 一句摘要）：\\n{query}"\n    body = {"contents": [{"role": "user", "parts": [{"text": prompt}]}]}\n\n    async with httpx.AsyncClient(timeout=15) as client:\n        try:\n            r = await client.post(url, json=body)\n            if r.status_code != 200:\n                return []\n            data = r.json()\n            text = data["candidates"][0]["content"]["parts"][0]["text"]\n            return [{"title": query, "snippet": text, "url": ""}]\n        except Exception:\n            return []\n',
}


def write_business(output_dir: Path) -> list[str]:
    created = []
    for rel_path, content in FILES.items():
        dst = output_dir / "src" / rel_path
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(content, encoding="utf-8")
        created.append(f"src/{rel_path}")
    
    return created
